import requests
from bs4 import BeautifulSoup
import os
# from openai import OpenAI # Uncomment if using OpenAI for categorization

# Configuration
TOPIC = "Python Programming Basics"
OUTPUT_FILE = "KNOWLEDGE_MAP.md"

def scrape_resources(topic):
    print(f"Searching for resources on: {topic}")
    # This is a simplified example. A real scraper would need to handle various websites.
    # For demonstration, we'll simulate finding some links.
    search_query = topic.replace(" ", "+")
    url = f"https://www.google.com/search?q={search_query}+tutorial"
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
    }
        
    try:
        response = requests.get(url, headers=headers)
        response.raise_for_status() # Raise an exception for HTTP errors
        soup = BeautifulSoup(response.text, 'html.parser')
            
        links = []
        for g in soup.find_all('div', class_='g'):
            a = g.find('a')
            if a and 'href' in a.attrs:
                link = a['href']
                title = g.find('h3')
                if title and link.startswith('http'): # Filter out non-external links
                    links.append({'title': title.get_text(), 'url': link})
        return links
    except requests.exceptions.RequestException as e:
        print(f"Error during scraping: {e}")
        return []

def categorize_resource(title, url):
    # This is a placeholder for AI categorization. 
    # For now, we'll use a simple keyword-based categorization.
    title_lower = title.lower()
    if "beginner" in title_lower or "introduction" in title_lower or "getting started" in title_lower:
        return "Beginner"
    elif "advanced" in title_lower or "deep dive" in title_lower or "expert" in title_lower:
        return "Advanced"
    else:
        return "Intermediate"

    # Uncomment the following for AI categorization (requires OpenAI API key)
    # client = OpenAI()
    # try:
    #     response = client.chat.completions.create(
    #         model="gpt-4.1-mini", # or gpt-4.1-nano, gemini-2.5-flash
    #         messages=[
    #             {"role": "system", "content": "You are a helpful assistant that categorizes educational resources into 'Beginner', 'Intermediate', or 'Advanced'."},
    #             {"role": "user", "content": f"Categorize the following resource: '{title}' ({url}). Category:"}
    #         ],
    #         max_tokens=10
    #     )
    #     category = response.choices[0].message.content.strip()
    #     if category in ["Beginner", "Intermediate", "Advanced"]:
    #         return category
    #     else:
    #         return "Intermediate" # Default if AI gives unexpected output
    # except Exception as e:
    #     print(f"Error with AI categorization: {e}")
    #     return "Intermediate"

def generate_knowledge_map(topic, resources):
    content = f"# Knowledge Map: {topic}\n\n"
    content += "This document is automatically generated by the Didactic Barnacle engine.\n\n"
        
    categories = {"Beginner": [], "Intermediate": [], "Advanced": []}
    for res in resources:
        category = categorize_resource(res['title'], res['url'])
        categories[category].append(res)

    for category_name in ["Beginner", "Intermediate", "Advanced"]:
        if categories[category_name]:
            content += f"## {category_name}\n\n"
            for res in categories[category_name]:
                content += f"*   [{res['title']}]({res['url']})\n"
            content += "\n"
        
    return content

def main():
    resources = scrape_resources(TOPIC)
    if resources:
        knowledge_map_content = generate_knowledge_map(TOPIC, resources)
        with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
            f.write(knowledge_map_content)
        print(f"Knowledge map generated: {OUTPUT_FILE}")
    else:
        print("No resources found or an error occurred.")

if __name__ == "__main__":
    main()
  
